// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIH2x45D1Cc5KO4uQxdYEJnBdW2_g1tR0',
    appId: '1:1038536143668:web:b203ecc9de3f475a14eb61',
    messagingSenderId: '1038536143668',
    projectId: 'social-960eb',
    authDomain: 'social-960eb.firebaseapp.com',
    storageBucket: 'social-960eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBZpZ-_RlXBQvylrcVcpL8lFOSuGMlUpU',
    appId: '1:1038536143668:android:62b9f4baff99285914eb61',
    messagingSenderId: '1038536143668',
    projectId: 'social-960eb',
    storageBucket: 'social-960eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIutEcD8pmwNAewpoZr5h9Nxi8qy81xI4',
    appId: '1:1038536143668:ios:55bd327b25aadaae14eb61',
    messagingSenderId: '1038536143668',
    projectId: 'social-960eb',
    storageBucket: 'social-960eb.firebasestorage.app',
    iosClientId: '1038536143668-28rfuk1ekbkl1n6guofb47p2oh3h2eee.apps.googleusercontent.com',
    iosBundleId: 'com.example.social',
  );
}
